CREATE TABLE IF NOT EXISTS ROLES (
  Rol_ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  Rol_Nombre VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS USUARIOS (
  Us_ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  Us_Nombre VARCHAR(50) NOT NULL,
  Us_Correo VARCHAR(50) NOT NULL UNIQUE,
  Us_Contraseña VARCHAR(20) NOT NULL,
  Us_Telefono VARCHAR(20),
  Us_Direccion VARCHAR(50),
  Rol_ID INT NOT NULL,
  FOREIGN KEY (Rol_ID) REFERENCES ROLES(Rol_ID)
);

-------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS CLIENTE (
  Cl_ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  Cl_RFC VARCHAR(13) NOT NULL,
  Cl_RazonSocial VARCHAR(100) NOT NULL,
  Cl_Nombre VARCHAR(50) NOT NULL,
  Cl_Domicilio VARCHAR(150) NOT NULL,
  Cl_CodigoPostal VARCHAR(10) NOT NULL,
  Cl_Correo VARCHAR(50) NOT NULL UNIQUE,
  Cl_Telefono VARCHAR(20),
  Cl_Colonia VARCHAR(50) NOT NULL,
  Cl_Ciudad VARCHAR(50) NOT NULL,
  Cl_Municipio VARCHAR(50) NOT NULL,
  Cl_Estado VARCHAR(50) NOT NULL,
  Cl_Pais VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS CONCEPTO_CARGO (
  Cc_ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  Cc_Descripcion VARCHAR(150) NOT NULL,
  Cc_Tipo VARCHAR(50) NOT NULL,
  Cc_Estatus VARCHAR(20)
);

CREATE TABLE IF NOT EXISTS CUENTA (
  Cu_ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  Cu_Nombre VARCHAR(50) NOT NULL,
  Cu_NumCuenta VARCHAR(20) NOT NULL,
  Cu_Direccion VARCHAR(50) NOT NULL, 
  Cu_Referencia VARCHAR(50),
  Cu_Telefono VARCHAR(20),   
  Cl_ID INT NOT NULL,
  FOREIGN KEY (Cl_ID) REFERENCES CLIENTE(Cl_ID)
);

CREATE TABLE IF NOT EXISTS TARIFA (
  Ta_ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  Ta_FechaInicio DATE NOT NULL,
  Ta_FechaFin DATE,
  Ta_Precio DECIMAL(10, 2) NOT NULL,
  Cc_ID INT NOT NULL,
  FOREIGN KEY (Cc_ID) REFERENCES CONCEPTO_CARGO(Cc_ID)
);

------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS CARGOS_SERVICIO (
  Cs_ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  Ta_ID INT NOT NULL,
  Cc_ID INT NOT NULL,
  Cu_ID INT NOT NULL,
  PRIMARY KEY (Ta_ID, Cc_ID, Cu_ID),
  FOREIGN KEY (Ta_ID) REFERENCES TARIFA(Ta_ID),
  FOREIGN KEY (Cc_ID) REFERENCES CONCEPTO_CARGO(Cc_ID),
  FOREIGN KEY (Cu_ID) REFERENCES CUENTA(Cu_ID)
);
------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS FACTURA (
  Fa_ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  Fa_DescDetallada VARCHAR(200),
  Fa_Cantidad INT NOT NULL,
  Fa_DescProducto VARCHAR(100) NOT NULL,
  Fa_Precio DECIMAL(10, 2) NOT NULL,
  Cu_ID INT NOT NULL,
  FOREIGN KEY (Cu_ID) REFERENCES CUENTA(Cu_ID)
);

CREATE TABLE IF NOT EXISTS PRODUCTO (
  Pr_ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  Pr_Codigo VARCHAR(20) NOT NULL, 
  Pr_Nombre VARCHAR(50) NOT NULL,
  Pr_Marca VARCHAR(50) NOT NULL,
  Pr_Modelo VARCHAR(50),
  Pr_Descripcion VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS CONCEPTO_SERVICIO (
  Cs_ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  Cs_NombreCliente VARCHAR(50) NOT NULL,
  Cs_RFC VARCHAR(13) NOT NULL,
  Cs_Tarifa DECIMAL(10, 2) NOT NULL,
  Cs_Descripcion VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS MATERIAL (
  Ma_ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  Ma_Nombre VARCHAR(50) NOT NULL,
  Ma_Marca VARCHAR(50) NOT NULL,
  Ma_Descripcion VARCHAR(100),
  Ma_PrecioUnitario DECIMAL(10, 2) NOT NULL,
  Ma_Stock INT NOT NULL
);

------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS DETALLE_MATERIAL (
  Os_ID INT NOT NULL,
  Ma_ID INT NOT NULL,
  Cs_ID INT NOT NULL,
  PRIMARY KEY (Os_ID, Ma_ID, Cs_ID),
  FOREIGN KEY (Os_ID) REFERENCES ORDEN_SERVICIO(Os_ID),
  FOREIGN KEY (Ma_ID) REFERENCES MATERIAL(Ma_ID),
  FOREIGN KEY (Cs_ID) REFERENCES CONCEPTO_SERVICIO(Cs_ID)
);
------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS ORDEN_SERVICIO (
  Os_ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  Os_Folio VARCHAR(20) NOT NULL, 
  Os_Cantidad INT NOT NULL,
  Os_Descripcion VARCHAR(100), 
  Os_Precio DECIMAL(10, 2) NOT NULL, 
  Cs_ID INT NOT NULL,
  FOREIGN KEY (Cs_ID) REFERENCES CONCEPTO_SERVICIO(Cs_ID)
);

CREATE TABLE IF NOT EXISTS DETALLE_FACTURA (
  Df_ID INT NOT NULL AUTO_INCREMENT,
  Fa_ID INT NOT NULL,
  Pr_ID INT,
  Ta_ID INT,
  Os_ID INT,
  Df_Descripcion VARCHAR(200),
  Df_PrecioUnitario DECIMAL(10, 2) NOT NULL,
  PRIMARY KEY (Df_ID),
  FOREIGN KEY (Fa_ID) REFERENCES FACTURA(Fa_ID),
  FOREIGN KEY (Pr_ID) REFERENCES PRODUCTO(Pr_ID),
  FOREIGN KEY (Ta_ID) REFERENCES CARGOS_SERVICIO(Ta_ID),
  FOREIGN KEY (Os_ID) REFERENCES ORDEN_SERVICIO(Os_ID)
);

CREATE TABLE IF NOT EXISTS CxC (
  Cu_ID INT NOT NULL,
  Fa_ID INT NOT NULL,
  PRIMARY KEY (Cu_ID, Fa_ID),
  FOREIGN KEY (Cu_ID) REFERENCES CUENTA(Cu_ID),
  FOREIGN KEY (Fa_ID) REFERENCES FACTURA(Fa_ID)
);
