CREATE TABLE IF NOT EXISTS ROLES (
  ROL_ID INT NOT NULL PRIMARY KEY,
  NombreRol VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS USUARIOS (
  US_ID INT NOT NULL PRIMARY KEY,
  Nombre VARCHAR(50) NOT NULL,
  Correo VARCHAR(50) NOT NULL UNIQUE,
  Contraseña VARCHAR(20) NOT NULL,
  Telefono VARCHAR(20),
  Direccion VARCHAR(50),
  ROL_ID INT NOT NULL,
  FOREIGN KEY (ROL_ID) REFERENCES ROLES(ROL_ID)
);

--------------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS CLIENTE (
  CL_ID INT NOT NULL PRIMARY KEY,
  RFC VARCHAR(13) NOT NULL,
  RazonSocial VARCHAR(100) NOT NULL,
  Nombre VARCHAR(50) NOT NULL,
  Domicilio VARCHAR(150) NOT NULL,
  CodigoPostal VARCHAR(10) NOT NULL,
  Correo VARCHAR(50) NOT NULL UNIQUE,
  Telefono VARCHAR(20),
  Colonia VARCHAR(50) NOT NULL,
  Ciudad VARCHAR(50) NOT NULL,
  Municipio VARCHAR(50) NOT NULL,
  Estado VARCHAR(50) NOT NULL,
  Pais VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS CONCEPTO_CARGO (
  CC_CLAVE INT NOT NULL PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS CUENTA (
  CU_ID INT NOT NULL PRIMARY KEY,
  Nombre VARCHAR(50) NOT NULL,
  Num_Cuenta VARCHAR(20) NOT NULL,
  Direccion VARCHAR(50) NOT NULL, 
  Referencia VARCHAR(50),
  Telefono VARCHAR(20),   
  CL_ID INT NOT NULL,
  FOREIGN KEY (CL_ID) REFERENCES CLIENTE(CL_ID)
);

CREATE TABLE IF NOT EXISTS TARIFA (
  TA_CLAVE INT NOT NULL PRIMARY KEY,
  CC_CLAVE INT NOT NULL,
  FOREIGN KEY (CC_CLAVE) REFERENCES CONCEPTO_CARGO(CC_CLAVE)
);

CREATE TABLE IF NOT EXISTS CARGOS_SERVICIO (
  TA_CLAVE INT NOT NULL,
  CC_CLAVE INT NOT NULL,
  CU_ID INT NOT NULL,
  PRIMARY KEY (TA_CLAVE, CC_CLAVE, CU_ID),
  FOREIGN KEY (TA_CLAVE) REFERENCES TARIFA(TA_CLAVE),
  FOREIGN KEY (CC_CLAVE) REFERENCES CONCEPTO_CARGO(CC_CLAVE),
  FOREIGN KEY (CU_ID) REFERENCES CUENTA(CU_ID)
);

CREATE TABLE IF NOT EXISTS FACTURA (
  FA_FOLIO INT NOT NULL PRIMARY KEY,
  Desc_Detallada VARCHAR(200),
  Desc_Ticket VARCHAR(100),
  CodigoBarras VARCHAR(50),
  CU_ID INT NOT NULL,
  FOREIGN KEY (CU_ID) REFERENCES CUENTA(CU_ID)
);

CREATE TABLE IF NOT EXISTS PRODUCTO (
  PR_CLAVE INT NOT NULL PRIMARY KEY,
  Clave VARCHAR(20) NOT NULL, 
  Nombre VARCHAR(50) NOT NULL,
  Marca VARCHAR(50) NOT NULL,
  Modelo VARCHAR(50),
  Descripcion VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS CONCEPTO_SERVICIO (
  CS_CLAVE INT NOT NULL PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS MATERIAL (
  MA_CLAVE INT NOT NULL PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS DETALLE_MATERIAL (
  OS_FOLIO INT NOT NULL,
  MA_CLAVE INT NOT NULL,
  CS_CLAVE INT NOT NULL,
  PRIMARY KEY (OS_FOLIO, MA_CLAVE, CS_CLAVE),
  FOREIGN KEY (OS_FOLIO) REFERENCES ORDEN_SERVICIO(OS_FOLIO),
  FOREIGN KEY (MA_CLAVE) REFERENCES MATERIAL(MA_CLAVE),
  FOREIGN KEY (CS_CLAVE) REFERENCES CONCEPTO_SERVICIO(CS_CLAVE)
);

CREATE TABLE IF NOT EXISTS ORDEN_SERVICIO (
  OS_CLAVE INT NOT NULL PRIMARY KEY,
  Folio VARCHAR(20) NOT NULL, 
  Cantidad INT NOT NULL,
  Descripcion VARCHAR(100), 
  Precio DECIMAL(10, 2) NOT NULL, 
  CS_CLAVE INT NOT NULL,
  FOREIGN KEY (CS_CLAVE) REFERENCES CONCEPTO_SERVICIO(CS_CLAVE)
);

CREATE TABLE IF NOT EXISTS DETALLE_FACTURA (
  DF_FOLIO INT NOT NULL,
  FA_FOLIO INT NOT NULL,
  DF_NUMERO VARCHAR(50) NOT NULL,
  PRIMARY KEY (DF_FOLIO, FA_FOLIO),
  FOREIGN KEY (FA_FOLIO) REFERENCES FACTURA(FA_FOLIO)
);

CREATE TABLE IF NOT EXISTS CxC (
  CU_ID INT NOT NULL,
  FA_FOLIO INT NOT NULL,
  PRIMARY KEY (CU_ID, FA_FOLIO),
  FOREIGN KEY (CU_ID) REFERENCES CUENTA(CU_ID),
  FOREIGN KEY (FA_FOLIO) REFERENCES FACTURA(FA_FOLIO)
);
