CREATE TABLE Roles (
  ROL_ID INT NOT NULL PRIMARY KEY,
  NombreRol VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE Usuarios (
  US_ID INT NOT NULL PRIMARY KEY,
  Nombre VARCHAR(50) NOT NULL,
  Correo VARCHAR(50) NOT NULL UNIQUE,
  Contraseña VARCHAR(20) NOT NULL,
  Telefono VARCHAR(20),
  Direccion VARCHAR(50),
  ROL_ID INT NOT NULL,
  FOREIGN KEY (ROL_ID) REFERENCES Roles(ROL_ID)
);

-------------------------------------------------------------

CREATE TABLE CLIENTE(
  CL_ID INT NOT NULL PRIMARY KEY,
  Nombre VARCHAR(50) NOT NULL,
  Correo VARCHAR(50) NOT NULL UNIQUE,
  Contraseña VARCHAR(20) NOT NULL,
  Telefono VARCHAR(20),
  Direccion VARCHAR(50)
);

CREATE TABLE CONCEPTO_CARGO(
  CC_CLAVE INT NOT NULL PRIMARY KEY
);

CREATE TABLE CUENTA(
  CU_ID INT NOT NULL PRIMARY KEY,
  CL_ID INT NOT NULL,
  FOREIGN KEY (CL_ID) REFERENCES CLIENTE(CL_ID)
);

CREATE TABLE TARIFA(
  TA_CLAVE INT NOT NULL PRIMARY KEY,
   CC_CLAVE INT NOT NULL,
   FOREIGN KEY (CC_CLAVE) REFERENCES CONCEPTO_CARGO(CC_CLAVE)
);

CREATE TABLE CARGOS_SERVICIO(
  TA_CLAVE INT NOT NULL PRIMARY KEY,
  CC_CLAVE INT NOT NULL PRIMARY KEY,
  CU_ID INT NOT NULL PRIMARY KEY,
  PRIMARY KEY (TA_CLAVE, CC_CLAVE, CU_ID),
  FOREIGN KEY (TA_CLAVE) REFERENCES TARIFA(TA_CLAVE),
  FOREIGN KEY (CC_CLAVE) REFERENCES CONCEPTO_CARGO(CC_CLAVE),
  FOREIGN KEY (CU_ID) REFERENCES CUENTA(CU_ID)
);
	
CREATE TABLE FACTURA(
  FA_FOLIO INT NOT NULL PRIMARY KEY,
  CU_ID INT NOT NULL,
  FOREIGN KEY (CU_ID) REFERENCES CUENTA(CU_ID)
);

CREATE TABLE PRODUCTO(
  PR_CLAVE INT NOT NULL PRIMARY KEY
);

CREATE TABLE CONCEPTO_SERVICIO(
  CS_CLAVE INT NOT NULL PRIMARY KEY
);

CREATE TABLE MATERIAL(
 MA_CLAVE INT NOT NULL PRIMARY KEY
);

CREATE TABLE DETALLE_MATERIAL(
  OS_FOLIO INT NOT NULL PRIMARY KEY,
  MA_CLAVE INT NOT NULL PRIMARY KEY,
  CS_FOLIO INT NOT NULL PRIMARY KEY,
  PRIMARY KEY (OS_FOLIO, MA_CLAVE, CS_CLAVE),
  FOREIGN KEY (OS_FOLIO) REFERENCES ORDEN_SERVICIO(OS_FOLIO),
  FOREIGN KEY (MA_CLAVE) REFERENCES MATERIAL(MA_CLAVE),
  FOREIGN KEY (CS_CLAVE) REFERENCES CONCEPTO_SERVICIO(CS_CLAVE)
);

CREATE TABLE ORDEN_SERVICIO(
  OS_FOLIO INT NOT NULL PRIMARY KEY,
  CS_CLAVE INT NOT NULL,
  FOREIGN KEY (CS_CLAVE) REFERENCES CONCEPTO_SERVICIO(CS_CLAVE)
);

CREATE TABLE DETALLE_FACTURA(
  DF_FOLIO INT NOT NULL PRIMARY KEY,
  FA_FOLIO INT NOT NULL PRIMARY KEY,
  DF_NUMERO VARCHAR(50) NOT NULL,
  FOREIGN KEY (FA_FOLIO) REFERENCES FACTURA(FA_FOLIO)
);

CREATE TABLE CxC(
  CU_ID INT NOT NULL,
  FA_FOLIO INT NOT NULL,
  PRIMARY KEY (CU_ID, FA_FOLIO),
  FOREIGN KEY (CU_ID) REFERENCES CUENTA(CU_ID),
  FOREIGN KEY (FA_FOLIO) REFERENCES FACTURA(FA_FOLIO)
);

